#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() { echo -e "${BLUE}ℹ ${NC}$1"; }
print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }

# Detect sed in-place syntax (macOS/BSD vs GNU/Linux)
# macOS/BSD sed requires: sed -i '' 
# GNU/Linux sed requires: sed -i
if sed --version >/dev/null 2>&1; then
    # GNU sed (Linux)
    SED_INPLACE="sed -i"
else
    # BSD sed (macOS)
    SED_INPLACE="sed -i ''"
fi

# Check if branch name is provided
if [ -z "$1" ]; then
    print_error "Usage: ./scripts/new-worktree.sh <branch-name> [base-branch]"
    echo "Example: ./scripts/new-worktree.sh feature/new-ui main"
    exit 1
fi

BRANCH_NAME=$1
BASE_BRANCH=${2:-main}  # Default to 'main' if not provided
WORKTREE_DIR="../${PWD##*/}-${BRANCH_NAME//\//-}"  # Convert feature/new-ui to feature-new-ui

print_info "Setting up new worktree for branch: $BRANCH_NAME"

# Step 1: Find available port pair
print_info "Finding available ports..."
API_PORT=3001
WEB_PORT=3000

while lsof -Pi :$API_PORT -sTCP:LISTEN -t >/dev/null 2>&1; do
    API_PORT=$((API_PORT + 1000))
    WEB_PORT=$((WEB_PORT + 1000))
done

print_success "Found available ports: API=$API_PORT, WEB=$WEB_PORT"

# Step 2: Create worktree
print_info "Creating worktree at $WORKTREE_DIR..."

# Check if branch exists
if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
    print_warning "Branch '$BRANCH_NAME' already exists, checking it out..."
    git worktree add "$WORKTREE_DIR" "$BRANCH_NAME"
else
    print_info "Creating new branch '$BRANCH_NAME' from '$BASE_BRANCH'..."
    git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR" "$BASE_BRANCH"
fi

if [ $? -ne 0 ]; then
    print_error "Failed to create worktree"
    exit 1
fi

print_success "Worktree created at $WORKTREE_DIR"

# Step 3: Create .env with unique ports
print_info "Creating .env with ports $API_PORT and $WEB_PORT..."

# Check if .env exists in main repo
if [ ! -f .env ]; then
    print_error ".env file not found in main repository"
    print_info "Please create a .env file first, then try again"
    exit 1
fi

# Copy the entire .env file to worktree
cp .env "$WORKTREE_DIR/.env"

# Add worktree header
eval "$SED_INPLACE" "'1i\\
# Auto-generated by new-worktree.sh\\
# Worktree: $BRANCH_NAME\\
# Created: $(date)\\
# Ports: API=$API_PORT WEB=$WEB_PORT\\
\\

' \"$WORKTREE_DIR/.env\""

# Replace port-specific values using sed
if ! cd "$WORKTREE_DIR"; then
    print_error "Failed to enter worktree directory: $WORKTREE_DIR"
    exit 1
fi

eval "$SED_INPLACE" '"s|^PORT=.*|PORT=$API_PORT|" .env'
eval "$SED_INPLACE" '"s|^VITE_PORT=.*|VITE_PORT=$WEB_PORT|" .env'
eval "$SED_INPLACE" '"s|^VITE_API_URL=.*|VITE_API_URL=http://localhost:$API_PORT|" .env'
eval "$SED_INPLACE" '"s|^BETTER_AUTH_URL=.*|BETTER_AUTH_URL=http://localhost:$API_PORT|" .env'
eval "$SED_INPLACE" '"s|^APP_URL=.*|APP_URL=http://localhost:$WEB_PORT|" .env'

# Add the variables if they don't exist
grep -q "^VITE_PORT=" .env || echo "VITE_PORT=$WEB_PORT" >> .env
grep -q "^VITE_API_URL=" .env || echo "VITE_API_URL=http://localhost:$API_PORT" >> .env

print_success ".env created with all environment variables"

# Step 4: Install dependencies and create helper scripts in worktree
print_info "Installing dependencies in worktree..."

pnpm install

if [ $? -ne 0 ]; then
    print_warning "Dependency installation had warnings, but continuing..."
fi

print_success "Dependencies installed"

# Step 5: Create helper scripts
print_info "Creating helper scripts..."

# Create a start script
cat > "dev.sh" << 'DEVSCRIPT'
#!/bin/bash
# Start dev server (worktree has its own .env file)
pnpm dev
DEVSCRIPT

chmod +x dev.sh

# Create a README for this worktree
cat > "WORKTREE.md" << EOF
# Worktree: $BRANCH_NAME

**Created:** $(date)
**Ports:** API=$API_PORT, WEB=$WEB_PORT

## Quick Start

\`\`\`bash
# Start development servers
./dev.sh

# Or manually
pnpm dev
\`\`\`

## Access URLs

- **Web App:** http://localhost:$WEB_PORT
- **API:** http://localhost:$API_PORT
- **tRPC:** http://localhost:$API_PORT/trpc

## Commit & Push

\`\`\`bash
git add .
git commit -m "feat: your message"
git push origin "$BRANCH_NAME"
\`\`\`

## Clean Up

When done with this worktree:

\`\`\`bash
# From main repo
cd ../${PWD##*/}
git worktree remove "$WORKTREE_DIR"
git branch -d "$BRANCH_NAME"  # if merged
\`\`\`

## Claude Code Tips

- This worktree is fully isolated
- Changes here don't affect other worktrees
- Commits go directly to branch: $BRANCH_NAME
- Environment configured for ports: $API_PORT/$WEB_PORT
EOF

print_success "Helper scripts created"

# Step 6: Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
print_success "Worktree setup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Location:    $WORKTREE_DIR"
echo "🌿 Branch:      $BRANCH_NAME"
echo "🔌 API Port:    $API_PORT"
echo "🌐 Web Port:    $WEB_PORT"
echo ""
echo "🚀 Next steps:"
echo ""
echo "   cd $WORKTREE_DIR"
echo "   ./dev.sh"
echo ""
echo "   Then open http://localhost:$WEB_PORT"
echo ""
echo "💡 Open this worktree in a new Claude Code window to work on it"
echo "   File → Open Folder → $WORKTREE_DIR"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

